In [2]:
import pandas as pd
from tqdm import tqdm
import os

In [3]:
data_train = pd.read_csv("df_train.csv")
data_test = pd.read_csv("df_test.csv")
data_val = pd.read_csv("df_val.csv")

In [4]:
data_train

,Unnamed: 0.1,Unnamed: 0,gameId,matchId,gameVersion,gameDuration,teamVictory,team_100_gold,team_200_gold,Player_id,...,Player_10_role,Player_10_team,Player_10_victory,Player_10_position,Player_10_time_game,Player_10_gold,Player_10_xp,Player_10_dmg_dealt,Player_10_dmg_taken,Player_10_time_ccing
0,0,0,398776824,RU_398776824,12.12.450.4196,1837,100,65405,58915,10,...,SUPPORT,200,0,UTILITY,1837,7847,10195,6120,24057,28
1,1,0,4363972028,NA1_4363972028,12.12.450.4196,1566,200,48274,55955,10,...,SUPPORT,200,1,UTILITY,1566,7619,9623,4525,8963,41
2,2,0,3168495552,EUN1_3168495552,12.12.450.4196,1572,200,48206,61837,10,...,NONE,200,1,UTILITY,1572,13997,12369,28012,13220,27
3,3,0,1314237530,TR1_1314237530,12.12.450.4196,1901,100,72646,64186,10,...,SUPPORT,200,0,UTILITY,1901,8702,12848,15059,33510,63
4,4,0,1193729142,LA2_1193729142,12.12.450.4196,1485,200,36338,55458,10,...,SOLO,200,1,UTILITY,1485,8617,11778,8615,6494,24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86631,86631,0,5964301583,EUW1_5964301583,12.12.450.4196,926,200,23857,35131,10,...,SUPPORT,200,1,UTILITY,926,4869,4186,3006,4811,10
86632,86632,0,5953381872,EUW1_5953381872,12.12.450.4196,1235,200,32813,38548,10,...,SUPPORT,200,1,UTILITY,1235,5714,7042,3500,5675,38
86633,86633,0,2553762406,BR1_2553762406,12.12.450.4196,1619,100,55793,48927,10,...,SUPPORT,200,0,UTILITY,1619,6664,8706,7787,12810,25
86634,86634,0,5950633298,EUW1_5950633298,12.12.450.4196,1117,100,40186,26627,10,...,SUPPORT,200,0,UTILITY,1117,3897,3676,2682,7051,11
86635,86635,0,5949308432,EUW1_5949308432,12.12.450.4196,1622,200,51575,59296,10,...,SUPPORT,200,1,UTILITY,1622,9151,11631,16459,8584,26

In [5]:
data_train['Player_1_pick'].unique()

array([516, 150,  50, 420,  98,  10, 887,  40, 154,  80,   8, 266,  48,
        26,  82, 875,  68,  41, 246,  69,  31, 145, 114, 777,   2,  81,
        62,  58,  79, 106,  27, 117, 122,  86,  39,  84, 164,  78,  54,
       157,  61, 166, 350, 126,  85, 133, 131,  36,  92,  24,  22,  23,
        75, 240, 523, 113, 236, 115, 876,  19,  16, 107, 104,  74, 221,
        43, 119, 234,  14,   6, 526,  17,   5, 238, 517,  67, 102,  38,
        56, 103, 223, 518, 112, 147,  37, 267,   9,   3,  83,  91,  30,
        42, 235,  55, 127,  28, 245, 360,  90,  72, 136,  18,  76,  34,
       202,  11,  64, 268, 429, 555, 200,  25,  21, 498, 120, 432,  57,
        44,  13,  45, 222, 203, 111, 163, 427, 101, 110,   7, 888,  59,
       161,  63,  12, 141,  77, 412,  32,  29,  35,  15,   1,  51, 142,
        99,   4, 421,  53,  89, 134, 121,  20,  33, 201,  96, 105, 497,
       711, 143, 254,  60])

In [6]:
train_gid = data_train['gameId']
test_gid = data_train['gameId']
train_gid

0         398776824
1        4363972028
2        3168495552
3        1314237530
4        1193729142
            ...
86631    5964301583
86632    5953381872
86633    2553762406
86634    5950633298
86635    5949308432
Name: gameId, Length: 86636, dtype: int64

In [7]:
print ( '398776824' in train_gid)

False