In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../processed_data/train.csv")

In [3]:
# define useless columns
drop_columns = ['gameId']

prefix = "Player_"
suffixs =["_pick","_position","_time_game"]
for i in range(1,11):
    for suffix in suffixs:
        drop_columns.append(prefix+str(i)+suffix)

drop_columns

['gameId',
 'Player_1_pick',
 'Player_1_position',
 'Player_1_time_game',
 'Player_2_pick',
 'Player_2_position',
 'Player_2_time_game',
 'Player_3_pick',
 'Player_3_position',
 'Player_3_time_game',
 'Player_4_pick',
 'Player_4_position',
 'Player_4_time_game',
 'Player_5_pick',
 'Player_5_position',
 'Player_5_time_game',
 'Player_6_pick',
 'Player_6_position',
 'Player_6_time_game',
 'Player_7_pick',
 'Player_7_position',
 'Player_7_time_game',
 'Player_8_pick',
 'Player_8_position',
 'Player_8_time_game',
 'Player_9_pick',
 'Player_9_position',
 'Player_9_time_game',
 'Player_10_pick',
 'Player_10_position',
 'Player_10_time_game']

In [4]:
df.drop(drop_columns, axis=1, inplace=True)

In [8]:
df = df.rename(columns={'teamVictory':'TeamVictory'})

In [9]:
df

,gameDuration,TeamVictory,team_100_gold,team_200_gold,Player_1_gold,Player_1_xp,Player_1_dmg_dealt,Player_1_dmg_taken,Player_1_time_ccing,Player_2_gold,...,Player_9_gold,Player_9_xp,Player_9_dmg_dealt,Player_9_dmg_taken,Player_9_time_ccing,Player_10_gold,Player_10_xp,Player_10_dmg_dealt,Player_10_dmg_taken,Player_10_time_ccing
0,1837,100,65405,58915,11898,15994,18417,28483,34,13231,...,17073,14537,38695,23943,8,7847,10195,6120,24057,28
1,1566,200,48274,55955,11144,13246,16323,26511,22,8545,...,14159,12228,20082,13158,18,7619,9623,4525,8963,41
2,1572,200,48206,61837,11770,13555,26124,31352,49,9761,...,11721,13829,17595,18734,18,13997,12369,28012,13220,27
3,1901,100,72646,64186,16797,18448,50448,57034,10,14614,...,19610,16417,46908,30680,5,8702,12848,15059,33510,63
4,1485,200,36338,55458,7108,10690,10147,22186,23,6668,...,10628,9816,16346,20530,2,8617,11778,8615,6494,24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85758,1893,100,70023,65105,9030,12912,10110,34832,24,13957,...,12597,13204,22384,28660,21,11601,12654,23098,22031,50
85759,913,200,23224,34077,4673,6238,4370,6867,5,4531,...,7468,6343,7814,4680,0,4239,4487,3757,7548,28
85760,1838,200,53520,63474,10033,12691,6817,24497,17,10946,...,16632,15810,30335,16915,2,9638,12985,11833,19067,39
85761,800,200,18019,30387,5504,6430,9909,12221,4,3322,...,6168,4954,8083,4253,0,4738,4012,2730,3028,5
85762,926,200,23857,35131,4900,7153,3946,8438,3,4222,...,7340,5353,5607,7338,3,4869,4186,3006,4811,10

In [10]:
df.to_csv("exploredata1.csv",index=False)